### ISSUE TITLE
Long check transactions time

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/gomu-gomu-no-gatling#18]
At the moment checking 1200 txs takes around 27 minutes on a Macbook Pro M1. This time should decrease by a lot. This might be related to some madara update (last weeks the time was lower)

<img width="975" alt="image" src="https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/assets/5263301/debf6ed4-c218-439e-b0b5-e9dbeb1cf63f">

**Comment by haroune-mohammedi** [comment]
So, after thorough investigation we are now sure the problem comes from madara, in fact we made `katana` compatible with gatling and test against it and it takes less than a second to check all the transactions

This issue should be fixed by https://github.com/keep-starknet-strange/madara/issues/1295

Also, @EvolveArt said we should first test against sharingan which will be updated soon to be sure this issue is related to local deployments
